# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/matvey/UnrealEngine
GAMEPROJECTFILE =/home/matvey/Documents/unreal_projects/TheWalkerGame/TheWalkerGame.uproject

TARGETS = \
	TheWalkerGame-Linux-Debug  \
	TheWalkerGame-Linux-DebugGame  \
	TheWalkerGame-Linux-Test  \
	TheWalkerGame-Linux-Shipping  \
	TheWalkerGame \
	TheWalkerGameEditor-Linux-Debug  \
	TheWalkerGameEditor-Linux-DebugGame  \
	TheWalkerGameEditor-Linux-Test  \
	TheWalkerGameEditor-Linux-Shipping  \
	TheWalkerGameEditor \
	UnrealClient-Linux-Debug  \
	UnrealClient-Linux-DebugGame  \
	UnrealClient-Linux-Test  \
	UnrealClient-Linux-Shipping  \
	UnrealClient \
	UnrealEditor-Linux-Debug  \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Test  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-Debug  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Test  \
	UnrealGame-Linux-Shipping  \
	UnrealGame \
	UnrealServer-Linux-Debug  \
	UnrealServer-Linux-DebugGame  \
	UnrealServer-Linux-Test  \
	UnrealServer-Linux-Shipping  \
	UnrealServer\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend TheWalkerGameEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug TheWalkerGameEditor-Linux-Debug


TheWalkerGame-Linux-Debug:
	 $(PROJECTBUILD) TheWalkerGame Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

TheWalkerGame-Linux-DebugGame:
	 $(PROJECTBUILD) TheWalkerGame Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

TheWalkerGame-Linux-Test:
	 $(PROJECTBUILD) TheWalkerGame Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

TheWalkerGame-Linux-Shipping:
	 $(PROJECTBUILD) TheWalkerGame Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

TheWalkerGame:
	 $(PROJECTBUILD) TheWalkerGame Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

TheWalkerGameEditor-Linux-Debug:
	 $(PROJECTBUILD) TheWalkerGameEditor Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

TheWalkerGameEditor-Linux-DebugGame:
	 $(PROJECTBUILD) TheWalkerGameEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

TheWalkerGameEditor-Linux-Test:
	 $(PROJECTBUILD) TheWalkerGameEditor Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

TheWalkerGameEditor-Linux-Shipping:
	 $(PROJECTBUILD) TheWalkerGameEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

TheWalkerGameEditor:
	 $(PROJECTBUILD) TheWalkerGameEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealClient-Linux-Debug:
	 $(BUILD) UnrealClient Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealClient-Linux-DebugGame:
	 $(BUILD) UnrealClient Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealClient-Linux-Test:
	 $(BUILD) UnrealClient Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealClient-Linux-Shipping:
	 $(BUILD) UnrealClient Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealClient:
	 $(BUILD) UnrealClient Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Debug:
	 $(BUILD) UnrealEditor Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Test:
	 $(BUILD) UnrealEditor Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Debug:
	 $(BUILD) UnrealGame Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Test:
	 $(BUILD) UnrealGame Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealServer-Linux-Debug:
	 $(BUILD) UnrealServer Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealServer-Linux-DebugGame:
	 $(BUILD) UnrealServer Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealServer-Linux-Test:
	 $(BUILD) UnrealServer Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealServer-Linux-Shipping:
	 $(BUILD) UnrealServer Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealServer:
	 $(BUILD) UnrealServer Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
